const GET_ACCOMMODATIONS = "GET_ACCOMMODATIONS";
const GET_ACCOMMODATION_BY_ID = "GET_ACCOMMODATION_BY_ID";
const GET_SERVICES = "GET_SERVICES"
const GET_NEXT_ACCOMMODATIONS = "GET_NEXT_ACCOMMODATIONS";
const GET_FILTERED_ACCOMMODATION = "GET_FILTERED_ACCOMMODATION"
const GET_LOCATIONS = "GET_LOCATIONS";
const GET_COUNTRIES = "GET_COUNTRIES"
const GET_CITIES = "GET_CITIES"
const ORDER_BY_RATING = "ORDER_BY_RATING";
const CLEAR_DETAIL = "CLEAR_DETAIL";
const CLEAR_DETAIL_TO_RESERVATION = "CLEAR_DETAIL_TO_RESERVATION";
const LOGIN_USER = "LOGIN_USER";
const LOGIN_GOOGLE = "LOGIN_GOOGLE";
const REGISTER_USER = "REGISTER_USER";
const GET_USER_DATA = "GET_USER_DATA";
const SET_RESERVATION_DATA = "SET_RESERVATION_DATA"
const UPDATE_USER_INFO = "UPDATE_USER_INFO";
const LOG_OUT = "LOG_OUT";
const GET_RESERVATION_BY_ID = "GET_RESERVATION_BY_ID"
const GET_USER_BY_ID_CHECKOUT = "GET_USER_BY_ID_CHECKOUT"

//!__________________________________ ADMIN __________________________________

const GET_ACTIVE_ACCOMMODATION = "GET_ACTIVE_ACCOMMODATION"
const GET_ACCOMMODATION_PENDING_CONFIRMATION = "GET_ACCOMMODATION_PENDING_CONFIRMATION"
const GET_DISABLED_ACCOMMODATION = "GET_DISABLED_ACCOMMODATION"
const GET_ALL_ACCOMMODATION = "GET_ALL_ACCOMMODATION"
const GET_ACCOMMODATION_PERCENTAGE = "GET_ACCOMMODATION_PERCENTAGE"
const DELETE_ACCOMMODATION = "DELETE_ACCOMMODATION"
const GET_ACCOMMODATION_BY_ID_A = "GET_ACCOMMODATION_BY_ID_A"
const UPDATE_ACCOMMODATION = "UPDATE_ACCOMMODATION"
const GET_ALL_USERS = "GET_ALL_USERS"
const GET_USERS_ACTIVES = "GET_USERS_ACTIVES"
const GET_USERS_ACTIVES_FALSE = "GET_USERS_ACTIVES_FALSE"
const GET_USER_BY_ID = "GET_USER_BY_ID"
const LOGIN_USER_A = "LOGIN_USER_A"
const DELETE_USER = "DELETE_USER"
const UPDATE_USER = "UPDATE_USER"
const GET_ACTIVE_REVIEWS = "GET_ACTIVE_REVIEWS"
const GET_REVIEWS_PENDING_CONFIRMATION = "GET_REVIEWS_PENDING_CONFIRMATION"
const GET_REVIEWS_DISABLED = "GET_REVIEWS_DISABLED"

export {
  ORDER_BY_RATING,
  GET_ACCOMMODATIONS,
  GET_ACCOMMODATION_BY_ID,
  GET_SERVICES,
  GET_NEXT_ACCOMMODATIONS,
  GET_FILTERED_ACCOMMODATION,
  GET_COUNTRIES,
  GET_CITIES,
  GET_LOCATIONS,
  CLEAR_DETAIL,
  CLEAR_DETAIL_TO_RESERVATION,
  LOGIN_USER,
  LOGIN_GOOGLE,
  REGISTER_USER,
  GET_USER_DATA,
  SET_RESERVATION_DATA,
  UPDATE_USER_INFO,
  LOG_OUT,
  GET_RESERVATION_BY_ID,
  GET_USER_BY_ID_CHECKOUT,
  //_____ADMIN_____
  GET_ACTIVE_ACCOMMODATION,
  GET_ACCOMMODATION_PENDING_CONFIRMATION,
  GET_DISABLED_ACCOMMODATION,
  GET_ALL_ACCOMMODATION,
  GET_ACCOMMODATION_PERCENTAGE,
  DELETE_ACCOMMODATION,
  GET_ACCOMMODATION_BY_ID_A,
  UPDATE_ACCOMMODATION,
  GET_ALL_USERS,
  GET_USERS_ACTIVES,
  GET_USERS_ACTIVES_FALSE,
  GET_USER_BY_ID,
  LOGIN_USER_A,
  DELETE_USER,
  UPDATE_USER,
  GET_ACTIVE_REVIEWS,
  GET_REVIEWS_PENDING_CONFIRMATION,
  GET_REVIEWS_DISABLED
}